[package]
name="speedleacher"
version="0.0.1"
edition="2021"

[dependencies]
exitcode = "1.1.2"
regex = "1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_bencode = "^0.2.3"
